(function(){var d=window||process;d.Appacitive||(d.Appacitive={runtime:{isNode:"undefined"!=typeof process,isBrowser:"undefined"!=typeof window}});var e=function(a){if(!a||!a.send||"function"!=typeof a.send)throw Error("No applicable httpTransport class found");a.onResponse=this.onResponse;var c=[],b={},d=0,g={},e=0;this.addProcessor=function(a){if(a){a.pre=a.pre||function(){};a.post=a.post||function(){};var c=a.pre;d+=1;b[d]=c;a=a.post;e+=1;g[e]=a}};this.enqueueRequest=function(a){c.push(a)};this.notify=
function(){if(0!=c.length){var d=[],h;for(h in g)g.hasOwnProperty(h)&&d.push(g[h]);for(;0<c.length;){var e=c.shift(),l=[];for(h in b)b.hasOwnProperty(h)&&l.push(b[h](e));a.send(e,d,l)}}};this.onResponse=function(a){console.dir(a)}},b=function(){var a=function(){throw Error("Not Implemented Exception");};this.inOnline=this.send=a;this.onResponse=function(){a()};this.onError=function(){a()}},a=function(){var a=new b;a.type="jQuery based http provider";a.send=function(a,b,f){"function"==typeof a.beforeSend&&
a.beforeSend(a);switch(a.method.toLowerCase()){case "get":$.ajax({url:a.url,type:"GET",async:a.async,beforeSend:function(c){for(var b=0;b<a.headers.length;b+=1)c.setRequestHeader(a.headers[b].key,a.headers[b].value)},success:function(e){try{e=JSON.parse(e)}catch(m){}c(e,b,f);d.onResponse(e,a)},error:function(){d.onError(a)}});break;case "post":$.ajax({url:a.url,type:"POST",async:a.async,contentType:"application/json",data:JSON.stringify(a.data),beforeSend:function(c){for(var b=0;b<a.headers.length;b+=
1)c.setRequestHeader(a.headers[b].key,a.headers[b].value)},success:function(e){try{e=JSON.parse(e)}catch(m){}c(e,b,f);d.onResponse(e,a)},error:function(){d.onError(a)}});break;case "put":$.ajax({url:a.url,type:"PUT",contentType:"application/json",data:JSON.stringify(a.data),async:a.async,beforeSend:function(c){for(var b=0;b<a.headers.length;b+=1)c.setRequestHeader(a.headers[b].key,a.headers[b].value)},success:function(e){try{e=JSON.parse(e)}catch(m){}c(e,b,f);d.onResponse(e,a)},error:function(){d.onError(a)}});
break;case "delete":$.ajax({url:a.url,type:"DELETE",async:a.async,beforeSend:function(c){for(var b=0;b<a.headers.length;b+=1)c.setRequestHeader(a.headers[b].key,a.headers[b].value)},success:function(e){try{e=JSON.parse(e)}catch(m){}c(e,b,f);d.onResponse(e,a)},error:function(){d.onError(a)}});break;default:throw Error("Unrecognized http method: "+a.method);}};a.isOnline=function(){return window.navigator.onLine||!0};var c=function(a,c,b){if(c.length!=b.length)throw Error("Callback length and state length mismatch!");
for(var f=0;f<c.length;f+=1)c[f].apply({},[a,b[f]])},d=a;$=$||{};$.ajax=$.ajax||{};return a};d.Appacitive.http=new function(){var c=(window||process).Appacitive.runtime.isBrowser?new a:NodeHttpTransport(),b=new e(c);_paused=!1;this.pause=function(){_paused=!0};this.unpause=function(){_paused=!1};this.addProcessor=function(a){var c=Error('Must provide a processor object with either a "pre" function or a "post" function.');if(!a)throw c;if(!a.pre&&!a.post)throw c;b.addProcessor(a)};this.send=function(a){b.enqueueRequest(a);
c.isOnline()&&!1==_paused&&b.notify()};this.flush=function(a){a?b.notify():c.isOnline()&&b.notify()};this.onError=function(a){if(a.onError)if(a.context)a.onError.apply(a.context,[]);else a.onError()};c.onError=this.onError;this.onResponse=function(a,c){if(c.onSuccess)if(c.context)c.onSuccess.apply(c.context,[a]);else c.onSuccess(a)};c.onResponse=this.onResponse};d.Appacitive.HttpRequest=function(){this.url="";this.data={};this.async=!0;this.headers=[];this.method="GET"};d=window||process;d.Appacitive&&
d.Appacitive.http&&d.Appacitive.http.addProcessor({pre:function(){return(new Date).getTime()},post:function(a,c){var b=(new Date).getTime()-c;a._timeTakenInMilliseconds=b}});var c=window||process;c.Appacitive&&c.Appacitive.http&&c.Appacitive.http.addProcessor({pre:function(a){return a},post:function(a,b){c.Appacitive.session.isSessionValid(a)||(null!=c.Appacitive.session.get()&&(c.Appacitive.session.resetSession(),c.Appacitive.session.onSessionCreated=function(){c.Appacitive.http.unpause();c.Appacitive.http.flush();
c.Appacitive.session.onSessionCreated=function(){}},c.Appacitive.session.recreate(),c.Appacitive.http.pause()),c.Appacitive.http.send(b))}})})();
for(var t=0;0<t--;){var req1=new Appacitive.HttpRequest;req1.url="https://apis.appacitive.com/sessionservice.svc/getGraph?rawData=true&from=-1hours&target=stats.pgossamer.account{0}.application1918338163933441.deployment10938369762787624.success";req1.method="get";req1.headers=[{key:"appacitive-session",value:"BxqkdySwptR0C5iaJfWXd2+6bkWYtEmMYuPC77odDXE="},{key:"appacitive-environment",value:"sandbox"}];req1.onSuccess=function(d){console.dir(d)};req1.onError=function(){console.log("error occured")};
Appacitive.http.send(req1)}
(function(d){String.format=function(b,a){if(1>=arguments.length)return b;for(var c=arguments.length-2,f=0;f<=c;f++)b=b.replace(RegExp("\\{"+f+"\\}","gi"),arguments[f+1]);return b};String.prototype.toPascalCase=function(){return this.charAt(0).toUpperCase()+this.slice(1)};String.prototype.trimChar=function(b){var a=RegExp("^"+b),c=this;a.test(c)&&(c=c.slice(1,c.length));a=RegExp(b+"$");a.test(c)&&(c=c.slice(0,-1));return c};String.toSearchString=function(b){"undefined"==typeof b&&(b="");for(var a=
"",c=0;c<b.length;c+=1)-1==" .,;#".indexOf(b[c])&&(a+=b[c]);return a=a.toLowerCase()};String.contains=function(b,a){return-1!=b.indexOf(a)};String.startsWith=function(b,a){return 0==b.indexOf(a)};window.dateFromWcf=function(b,a){var c=/Date\(([^)]+)\)/.exec(b);if(2!=c.length){if(!a)return s;throw Error(s+" is not .net json date.");}return new Date(parseFloat(c[1]))};var e=function(){d.Appacitive=d.Appacitive||{};d.Appacitive.bag=d.Appacitive.bag||{};d.Appacitive.bag.accountName=d.Appacitive.bag.accountName||
{};d.Appacitive.bag.selectedType=d.Appacitive.bag.selectedType||{};d.Appacitive.bag.apps=d.Appacitive.bag.apps||{};d.Appacitive.bag.apps.selected=d.Appacitive.bag.apps.selected||{};d.Appacitive.bag.apps.selected.name=d.Appacitive.bag.apps.selected.name||{};d.Appacitive.bag.selectedCatalog=d.Appacitive.bag.selectedCatalog||{};d.Appacitive.bag.selectedCatalog.Id=d.Appacitive.bag.selectedCatalog.Id||0;d.Appacitive.bag.selectedCatalog.blueprintid=d.Appacitive.bag.selectedCatalog.blueprintid||0;d.Appacitive.bag.selectedCatalog.BlueprintId=
d.Appacitive.bag.selectedCatalog.BlueprintId||0;d.Appacitive.models=d.Appacitive.models||{};d.Appacitive.models.deploymentCollection=d.Appacitive.models.deploymentCollection||{};d.Appacitive.models.deploymentCollection.deployments=d.Appacitive.models.deploymentCollection.deployments||{};var b=(d.Appacitive.config||{apiBaseUrl:""}).apiBaseUrl;b.lastIndexOf("/")==b.length-1&&(b=b.substring(0,b.length-1));this.session={sessionServiceUrl:b+"/sessionservice",getCreateSessionUrl:function(a){return String.format("{0}/create?deploymentName={1}",
this.sessionServiceUrl,a)},getPingSessionUrl:function(){return String.format("{0}/ping",this.sessionServiceUrl)},getValidateTokenUrl:function(a){return String.format("{0}/validatetoken?token={1}",this.sessionServiceUrl,a)},getDeleteSessionUrl:function(a){return String.format("{0}/delete?deploymentName={1}",this.sessionServiceUrl,a)}};this.email={emailServiceUrl:"email",getSendEmailUrl:function(){return String.format("{0}/send",this.emailServiceUrl)}};this.identity={identityServiceUrl:b+"/accountservice",
getUpdateUserUrl:function(){return String.format("{0}/updateuser",this.identityServiceUrl)},getUserUrl:function(a){return String.format("{0}/user/{1}",this.identityServiceUrl,a)},getChangePasswordUrl:function(){return String.format("{0}/changepwd",this.identityServiceUrl)},getUploadUrl:function(a){return String.format("{0}/file/{1}",this.identityServiceUrl,a)}};this.user={userServiceUrl:b+"/user",getCreateUserUrl:function(){return String.format("{0}/create",this.userServiceUrl)},getAuthenticateUserUrl:function(){return String.format("{0}/authenticate",
this.userServiceUrl)},getUpdateUserUrl:function(a){return String.format("{0}/{1}",this.userServiceUrl,a)},getUserUrl:function(a){return String.format("{0}/{1}",this.userServiceUrl,a)},getUserDeleteUrl:function(a){return String.format("{0}/{1}",this.userServiceUrl,a)},getSearchAllUrl:function(a,c,b){a="";a=String.format("{0}/search/user/all",(new e).article.articleServiceUrl);a=b?a+"?psize="+b:a+"?psize=10";if("undefined"!==typeof c&&0<c.length)for(b=0;b<c.length;b+=1)0!=c[b].trim().length&&(a=a+"&"+
c[b]);return a},getGetAllLinkedAccountsUrl:function(a){return String.format("{0}/{1}/linkedaccounts",this.userServiceUrl,a)}};this.application={applicationServiceUrl:b+"/applicationservice",getSearchAllUrl:function(a){var c=String.format("{0}/find/{1}/all",this.applicationServiceUrl,d.Appacitive.bag.accountName);if("undefined"!==typeof a&&0<a.length)for(var b=0;b<a.length;b+=1)0<a[b].trim().length&&(c=c+"&"+a[b]);return c},getCreateUrl:function(){return String.format("{0}/create",this.applicationServiceUrl)},
getCreateSessionUrl:function(a){return String.format("{0}/session?appName={1}",this.applicationServiceUrl,a)},getDeleteUrl:function(a){return String.format("{0}/{1}",this.applicationServiceUrl,a)},getCheckNameUrl:function(a){return String.format("{0}/doesNameExist/{1}/{2}",this.applicationServiceUrl,d.Appacitive.bag.accountName,a)},getHasAppUrl:function(){return String.format("{0}/hasApp",this.applicationServiceUrl)},getGetPublishStatusUrl:function(a){return String.format("{0}/status/{1}",this.applicationServiceUrl,
a)},getGetUrl:function(a){return String.format("{0}/{1}",this.applicationServiceUrl,a)},getGenerateKeyUrl:function(a){return String.format("{0}/generatekey/{1}",this.applicationServiceUrl,a)},getUpdateKeyStatusUrl:function(a){return String.format("{0}/updatekey/{1}",this.applicationServiceUrl,a)},getUpdateApplicationUrl:function(a){return String.format("{0}/{1}",this.applicationServiceUrl,a)},getDeleteApiKey:function(a){return String.format("{0}/deletekey/{1}",this.applicationServiceUrl,a)},getUploadUrl:function(){return String.format("{0}/file/",
this.applicationServiceUrl)}};this.article={articleServiceUrl:b+"article",getExportUrl:function(a,c){return"Articles.exp?ctype=Article&blueprintid="+a+"&type="+c},getEntityId:function(){return d.Appacitive.bag.selectedCatalog.id},getGetUrl:function(a,c){return String.format("{0}/{1}/{2}",this.articleServiceUrl,a,c)},getMultiGetUrl:function(a,c,b){return String.format("{0}/multiGet/{1}/{2}",this.articleServiceUrl,c,b)},getMultiDeleteUrl:function(a,c){return String.format("{0}/multidelete/{1}",this.articleServiceUrl,
c)},getBlobUploadUrl:function(){return String.format("{0}/blob/upload",this.articleServiceUrl)},getBlobUpdateUrl:function(a){return String.format("{0}/blob/update?&articleid={1}",this.articleServiceUrl,a)},getSearchAllUrl:function(a,c,b,d){a="";a=String.format("{0}/search/{1}/all",this.articleServiceUrl,c);a=d?a+"?psize="+d:a+"?psize=10";if("undefined"!==typeof b&&0<b.length)for(c=0;c<b.length;c+=1)0!=b[c].trim().length&&(a=a+"&"+b[c]);return a},getProjectionQueryUrl:function(){return String.format("{0}/search/project",
this.articleServiceUrl)},getPropertiesSearchUrl:function(a,c,b){a=String.format("{0}/search/{1}/all",this.articleServiceUrl,c);return a+("?properties="+b)},getDeleteUrl:function(a,c){return String.format("{0}/{1}/{2}?verbose=true&debug=true",this.articleServiceUrl,a,c)},getCreateUrl:function(a){return String.format("{0}/{1}",this.articleServiceUrl,a)},getUpdateUrl:function(a,c){return String.format("{0}/{1}/{2}",this.articleServiceUrl,a,c)},getDownloadUrl:function(a){return String.format("article.file?fileurl="+
escape(a))}};this.catalog={catalogServiceUrl:b+"/blueprintservice",getSearchAllUrl:function(a){var c=String.format("{0}/find/all?",this.catalogServiceUrl),c=c+"?psize=1000";if("undefined"!==typeof a&&0<a.length)for(var b=0;b<a.length;b+=1)0!=a[b].trim().length&&(c=c+"&"+a[b]);return c},getPropertiesSearchUrl:function(a,c,b){a=String.format("{0}/search/{1}/{2}/all",this.articleServiceUrl,a,c);return a+("?properties="+b)},getDeleteUrl:function(a,c,b){return String.format("{0}/delete/{1}/{2}/{3}",this.articleServiceUrl,
a,c,b)},getCreateUrl:function(a){return String.format("{0}/create/{1}",this.articleServiceUrl,a)},getUpdateUrl:function(a,c){return String.format("{0}/update/{1}/{2}",this.articleServiceUrl,a,c)}};this.connection={connectionServiceUrl:b+"connection",getEntityId:function(){return d.Appacitive.bag.selectedCatalog.id},getGetUrl:function(a,c){return String.format("{0}/{1}/{2}",this.connectionServiceUrl,a,c)},getCreateUrl:function(a){return String.format("{0}/{1}",this.connectionServiceUrl,a)},getUpdateUrl:function(a,
c,b){return String.format("{0}/update/{1}/{2}",this.connectionServiceUrl,c,b)},getDeleteUrl:function(a,c){return String.format("{0}/{1}/{2}",this.connectionServiceUrl,a,c)},getMultiDeleteUrl:function(a,c){return String.format("{0}/multidelete/{1}",this.connectionServiceUrl,c)},getSearchByArticleUrl:function(a,c,b,d,e){a="";a=String.format("{0}/{1}/find/all?label={2}&articleid={3}",this.connectionServiceUrl,c,d,b);if("undefined"!==typeof e&&0<e.length)for(c=0;c<e.length;c+=1)a=a+"&"+e[c];return a},
getConnectedArticles:function(a,c,b,d){a="";a=String.format("{0}/{1}/{2}/find",this.connectionServiceUrl,c,b);if(d&&d.length&&0<d.length)for(c=0;c<d.length;c+=1)a=0==c?a+("?"+d[c]):a+("&"+d[c]);return a},getInterconnectsUrl:function(){var a="";return a=String.format("{0}/connectedarticles",this.connectionServiceUrl)},getPropertiesSearchUrl:function(a,c,b){a=String.format("{0}/{1}/find/all",this.connectionServiceUrl,c);return a+("?properties="+b)}};this.schema={schemaServiceUrl:b+"/schemaservice",
getEntityId:function(){return"deployment"==d.Appacitive.bag.selectedType?d.Appacitive.bag.selectedCatalog.blueprintid:d.Appacitive.bag.selectedCatalog.id},getExportUrl:function(a){return"Schemas.exp?ctype=Schema&blueprintid="+a},getSearchAllUrl:function(a,c){var b="";a&&(b=String.format("{0}/find/all/{1}",this.schemaServiceUrl,a));b+="?psize=200";if("undefined"!==typeof c&&0<c.length)for(var d=0;d<c.length;d+=1)b=b+"&"+c[d];return b},getGetPropertiesUrl:function(a){return String.format("{0}/get/{1}/{2}/true",
this.schemaServiceUrl,this.getEntityId(),a)},getCreateUrl:function(){return String.format("{0}/create/{1}",this.schemaServiceUrl,this.getEntityId())},getDeleteUrl:function(a){return String.format("{0}/delete/{1}/{2}",this.schemaServiceUrl,this.getEntityId(),a)},getUpdateUrl:function(a){return String.format("{0}/update/{1}/{2}",this.schemaServiceUrl,this.getEntityId(),a)},getUpdateAttributesUrl:function(a){return String.format("{0}/updateAttributes/{1}/{2}",this.schemaServiceUrl,this.getEntityId(),
a)},getAddPropertyUrl:function(a){return String.format("{0}/addProperty/{1}/{2}",this.schemaServiceUrl,this.getEntityId(),a)},getDeletePropertyUrl:function(a,c){return String.format("{0}/deleteProperty/{1}/{2}/{3}",this.schemaServiceUrl,this.getEntityId(),a,c)},getUpdatePropertyUrl:function(a){return String.format("{0}/updateProperty/{1}/{2}",this.schemaServiceUrl,this.getEntityId(),a)},getGetUrl:function(a){return String.format("{0}/get/{1}/{2}",this.schemaServiceUrl,"blueprint"==d.Appacitive.bag.selectedType?
d.Appacitive.bag.selectedCatalog.Id:d.Appacitive.bag.selectedCatalog.BlueprintId,a)}};this.relation={relationServiceUrl:b+"/relationservice",getEntityId:function(){return"deployment"==d.Appacitive.bag.selectedType?d.Appacitive.bag.selectedCatalog.blueprintid:d.Appacitive.bag.selectedCatalog.id},getExportUrl:function(a){return"Relations.exp?ctype=Relation&blueprintid="+a},getSearchBySchemaUrl:function(a,c,b){var d="",d=String.format("{0}/{1}/find/{2}",this.relationServiceUrl,a,c),d=d+"?psize=200";
if("undefined"!==typeof b&&0<b.length)for(a=0;a<b.length;a+=1)d=d+"&"+b[a];return d},getSearchAllUrl:function(a,c){var b="";a&&(b=String.format("{0}/find/all/{1}",this.relationServiceUrl,a));b+="?psize=200";if("undefined"!==typeof c&&0<c.length)for(var d=0;d<c.length;d+=1)b=b+"&"+c[d];return b},getGetPropertiesUrl:function(a){return String.format("{0}/get/{1}/{2}/true",this.relationServiceUrl,this.getEntityId(),a)},getCreateUrl:function(){return String.format("{0}/create/{1}",this.relationServiceUrl,
this.getEntityId())},getDeleteUrl:function(a){return String.format("{0}/delete/{1}/{2}",this.relationServiceUrl,this.getEntityId(),a)},getUpdateUrl:function(a){return String.format("{0}/update/{1}/{2}",this.relationServiceUrl,this.getEntityId(),a)},getUpdateAttributesUrl:function(a){return String.format("{0}/updateAttributes/{1}/{2}",this.relationServiceUrl,this.getEntityId(),a)},getAddPropertyUrl:function(a){return String.format("{0}/addProperty/{1}/{2}",this.relationServiceUrl,this.getEntityId(),
a)},getDeletePropertyUrl:function(a,c){return String.format("{0}/deleteProperty/{1}/{2}/{3}",this.relationServiceUrl,this.getEntityId(),a,c)},getUpdatePropertyUrl:function(a){return String.format("{0}/updateProperty/{1}/{2}",this.relationServiceUrl,this.getEntityId(),a)},getUpdateEndPointUrl:function(a,c){return String.format("{0}/updateEndpoint/{1}/{2}/{3}",this.relationServiceUrl,this.getEntityId(),a,c)},getGetUrl:function(a){return String.format("{0}/get/{1}/{2}",this.relationServiceUrl,"blueprint"==
d.Appacitive.bag.selectedType?d.Appacitive.bag.selectedCatalog.Id:d.Appacitive.bag.selectedCatalog.BlueprintId,a)}};this.cannedList={cannedListServiceUrl:b+"/listservice",getEntityId:function(){return"deployment"==d.Appacitive.bag.selectedType?d.Appacitive.bag.selectedCatalog.blueprintid:d.Appacitive.bag.selectedCatalog.id},getExportUrl:function(a){return"CannedLists.exp?ctype=List&blueprintid="+a},getListItemExportUrl:function(a,c){return"CannedLists.exp?ctype=ListItems&blueprintid="+a+"&type="+
c},getSearchAllUrl:function(a,c){var b="";a&&(b=String.format("{0}/find/all/{1}",this.cannedListServiceUrl,a));b+="?psize=200";if("undefined"!==typeof c&&0<c.length)for(var d=0;d<c.length;d+=1)b=b+"&"+c[d];return b},getGetItemsUrl:function(a){return String.format("{0}/get/{1}/{2}",this.cannedListServiceUrl,this.getEntityId(),a)},getCreateUrl:function(){return String.format("{0}/create/{1}",this.cannedListServiceUrl,this.getEntityId())},getDeleteUrl:function(a){return String.format("{0}/delete/{1}/{2}",
this.cannedListServiceUrl,this.getEntityId(),a)},getSearchListItemsUrl:function(a,c){var b=String.format("{0}/searchListItems/{1}/{2}",this.cannedListServiceUrl,this.getEntityId(),a);if("undefined"!==typeof c&&0<c.length){for(var b=b+"?",d=0;d<c.length;d+=1)b=b+c[d]+"&";b=b.substring(0,b.length-1)}return b},getUpdateListItemPositionUrl:function(a,b,d){return String.format("{0}/updateListItemPosition/{1}/{2}/{3}/{4}",this.cannedListServiceUrl,this.getEntityId(),a,b,d)},getDeleteListItemUrl:function(a,
b){return String.format("{0}/removeListItem/{1}/{2}/{3}",this.cannedListServiceUrl,this.getEntityId(),a,b)},getAddListItemsUrl:function(a){return String.format("{0}/addListItems/{1}/{2}",this.cannedListServiceUrl,this.getEntityId(),a)},getUpdateListItemUrl:function(a,b){return String.format("{0}/updateListItem/{1}/{2}/{3}",this.cannedListServiceUrl,this.getEntityId(),a,b)},getUpdateUrl:function(a){return String.format("{0}/update/{1}/{2}",this.cannedListServiceUrl,this.getEntityId(),a)},getGetUrl:function(a){return String.format("{0}/get/{1}/{2}",
this.cannedListServiceUrl,"blueprint"==d.Appacitive.bag.selectedType?d.Appacitive.bag.selectedCatalog.Id:d.Appacitive.bag.selectedCatalog.BlueprintId,a)}};this.catalog={catalogServiceUrl:b+"/blueprintservice",getSearchAllUrl:function(a){var b=String.format("{0}/find/all?",this.catalogServiceUrl),b=b+"?psize=1000";if("undefined"!==typeof a&&0<a.length)for(var d=0;d<a.length;d+=1)b=b+"&"+a[d];return b}};this.blueprint={blueprintServiceUrl:b+"/blueprintservice",getGetUrl:function(a){return String.format("{0}/get/{1}",
this.blueprintServiceUrl,a)},getDeleteUrl:function(a){return String.format("{0}/delete/{1}",this.blueprintServiceUrl,a)},getCreateUrl:function(){return String.format("{0}/create",this.blueprintServiceUrl)},getSchemasUrl:function(a){a=String.format("{0}/getSchemas/{1}?",this.blueprintServiceUrl,a);return a+"?psize=1000"},getRelationsUrl:function(a){a=String.format("{0}/{1}/contents/relations?",this.blueprintServiceUrl,a);return a+"?psize=1000"},getCannedListsUrl:function(a){a=String.format("{0}/{1}/contents/lists?",
this.blueprintServiceUrl,a);return a+"?psize=1000"}};this.deployment={deploymentServiceUrl:b+"/deploymentservice",getGetUrl:function(a){return String.format("{0}/get/{1}",this.deploymentServiceUrl,a)},getGetPublishStatusUrl:function(a){return String.format("{0}/status/{1}",this.deploymentServiceUrl,a)},getCreateUrl:function(){return String.format("{0}/create",this.deploymentServiceUrl)},getFetchAllDeploymentsUrl:function(){return String.format("{0}/fetchAll",this.deploymentServiceUrl)},getSearchAllSchemaUrl:function(a){a=
String.format("{0}/getSchemas/{1}",this.deploymentServiceUrl,a);return a+"?psize=1000"},getSearchAllRelationsUrl:function(a){a=String.format("{0}/getRelations/{1}",this.deploymentServiceUrl,a);return a+"?psize=1000"},getSearchAllListsUrl:function(a){a=String.format("{0}/getLists/{1}",this.deploymentServiceUrl,a);return a+"?psize=1000"},getExportUrl:function(a,b){return String.format("{0}/{1}/{2}",this.deploymentServiceUrl,a,b)},getMergeUrl:function(a,b){return String.format("{0}/{1}/{2}",this.deploymentServiceUrl,
a,b)},getUpdateDeployemntUrl:function(a){return String.format("{0}/{1}",this.deploymentServiceUrl,a)},getProfilerUrl:function(a){return String.format("{0}/profile/{1}?deploymentid={2}",this.deploymentServiceUrl,a,d.Appacitive.bag.selectedCatalog.id)},getLiveToStageUrl:function(){var a=d.Appacitive.models.deploymentCollection.deployments.filter(function(a){return a.name.toLowerCase()==d.Appacitive.bag.apps.selected.name.toLowerCase()})[0].id;return a=String.format("{0}/Execute/{1}/mergelivetosandbox?livedeploymentid={2}",
this.deploymentServiceUrl,"__Sandbox_"+d.Appacitive.bag.apps.selected.name,a)}};this.tag={tagServiceUrl:b+"/tagsservice",getEntityId:function(){return"deployment"==d.Appacitive.selectedType?d.Appacitive.bag.selectedCatalog.blueprintid:d.Appacitive.bag.selectedCatalog.id},getAddTagUrl:function(a,b,d,e){return String.format("{0}/addTag/{1}/{2}/{3}/{4}?tag={5}",this.tagServiceUrl,this.getEntityId(),a,b,d,e)},getRemoveTagUrl:function(a,b,d,e){return String.format("{0}/removeTag/{1}/{2}/{3}/{4}?tag={5}",
this.tagServiceUrl,this.getEntityId(),a,b,d,e)}};this.invoice={invoiceServiceUrl:b+"/invoiceservice",getUsageStatsUrl:function(){return this.invoiceServiceUrl+"/usage/"+d.Appacitive.bag.accountName}};this.account={accountServiceUrl:b+"/accountservice",getCreateNewAccountUrl:function(a){return String.format("{0}/createaccount?skipValid={1}",this.accountServiceUrl,a)},getAccountIdUrl:function(a){return this.accountServiceUrl+"/accountId/"+a},checkAccountNameUrl:function(a){return this.accountServiceUrl+
"/exists/"+a},createInvite:function(a){return String.format("{0}/createInvite?args={1}",this.accountServiceUrl,a)},requestInvite:function(){return this.accountServiceUrl+"/createtoken"},checkToken:function(a,b){return String.format("{0}/searchToken/{1}?skipValid={2}",this.accountServiceUrl,a,b)},isHuman:function(a,b){return this.accountServiceUrl+"/captcha/"+a+"/"+b}};this.query={params:function(a){var b=[];return""==location.search||-1==location.search.indexOf("?")?b:a?(a=a.toLowerCase(),location.search.split("?")[1].split("&").forEach(function(d,
e){var k=e.split("="),h=k[1];2<k.length&&k.forEach(function(a){0==a||1==a||(h=h+"="+k[a])});k[0].toLowerCase()==a&&(b=[k[0],h])}),b):location.search.split("?")[1].split("=")}};this.announcement={announcementServiceUrl:b+"/announcementservice",getSummaryUrl:function(){return this.announcementServiceUrl+"/summary"}};this.graphite={graphiteBaseUrl:b+"/sessionservice/getGraph",getBaseUrl:function(){return this.graphiteBaseUrl}};this.emailtemplate={emailTemplateServiceUrl:b+"/emailservice",getCreateUrl:function(){return this.emailTemplateServiceUrl+
"/create"},getUpdateUrl:function(a){return this.emailTemplateServiceUrl+"/"+a},getAllNames:function(){return this.emailTemplateServiceUrl+"/find/all"},getSearchByNameUrl:function(a){return this.emailTemplateServiceUrl+"/"+a},getDeleteUrl:function(a){return this.emailTemplateServiceUrl+"/"+a}}};d.Appacitive.storage=d.Appacitive.storage||{};d.Appacitive.storage.urlFactory=new e})(window||process);
(function(d){d.Appacitive.eventManager=new function(){var d={};this.subscribe=function(b,a){if("string"!=typeof b||"function"!=typeof a)throw Error("Incorrect subscription call");"undefined"==typeof d[b]&&(d[b]=[]);var c;c=function(){return Math.floor(65536*Math.random()).toString(16)};c=c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c();d[b].push({callback:a,id:c});return c};this.unsubscribe=function(b){if(!b)return!1;var a=-1,c=null,f;for(f in d)for(var j=0;j<d[f].length;j+=1)if(d[f][j].id==b){a=j;
c=f;break}return-1!=a?(d[c].splice(a,1),!0):!1};this.fire=function(b,a,c){if("string"!=typeof b)throw Error("Incorrect fire call");if("undefined"==typeof c||null==c)c={};c.eventName=b;console&&(console.log&&"function"==typeof console.log)&&console.log(b+" fired");if("undefined"!=typeof d.all)for(var f=0;f<d.all.length;f+=1)d.all[f].callback(a,c);if("undefined"!=typeof d[b])for(f=0;f<d[b].length;f+=1)(function(a,b,c){setTimeout(function(){a(b,c)},0)})(d[b][f].callback,a,c)};this.clearSubscriptions=
function(b){if("string"!=typeof b)throw Error("Event Name must be string in EventManager.clearSubscriptions");d[b]&&(d[b].length=0);return this};this.clearAndSubscribe=function(b,a){this.clearSubscriptions(b);this.subscribe(b,a)};this.dump=function(){console.dir(d)}}})(window||process);var _function=function(d,e){console.log("i subscribe to "+e.eventName)};window.Appacitive.eventManager.fire("unit.test");(function(d){d.Appacitive.config={apiBaseUrl:"https://apis.appacitive.com/"}})(window||process);
(function(d){d.Appacitive.session=new function(){var e=function(){this.apikey="";this.isnonsliding=!1;this.usagecount=-1;this.windowtime=240},b=null,a=null;this.onSessionCreated=function(){};this.recreate=function(){d.Appacitive.session.create(a)};this.create=function(c){if(null==b){a=c=c||{};var f=new e;f.apikey=c.apikey||"";f.isnonsliding=c.isnonsliding||f.isnonsliding;f.usagecount=c.usagecount||f.usagecount;f.windowtime=c.windowtime||f.windowtime;c=new Appacitive.HttpRequest;c.url=d.Appacitive.config.apiBaseUrl+
"application.svc/session";c.method="put";c.data=f;c.onSuccess=function(a){a&&a.status&&"200"==a.status.code?(b=a.session.sessionkey,d.Appacitive.eventManager.fire("session.success",{},a),d.Appacitive.http.addProcessor({pre:function(a){a.headers.push({key:"appacitive-session",value:b})}}),d.Appacitive.session.onSessionCreated()):d.Appacitive.eventManager.fire("session.error",{},a)};d.Appacitive.http.send(c)}};var c=null,f=!1;d.Appacitive.http.addProcessor({pre:function(a){!0==f&&(1==a.headers.filter(function(a){return"appacitive-user-auth"==
a.key}).length?a.headers.forEach(function(a){"appacitive-user-auth"==a.key&&(a.value=c)}):a.headers.push({key:"appacitive-user-auth",value:c}))}});this.setUserAuthHeader=function(a){f=!0;c=a};this.removeUserAuthHeader=function(){f=!1};this.isSessionValid=function(a){if(!a)return!0;if(a.status){if(a.status.code&&("8027"==a.status.code||"8002"==a.status.code))return!1}else if(a.code&&("8027"==a.code||"8002"==a.code))return!1;return!0};this.resetSession=function(){b=null};this.get=function(){return b};
var j="sandbox";this.__defineGetter__("environment",function(){return j});this.__defineSetter__("environment",function(a){"sandbox"!=a&&"live"!=a&&(a="sandbox");j=a})}})(window||process);(function(d){d.Appacitive&&d.Appacitive.http&&d.Appacitive.http.addProcessor({pre:function(e){e.headers.push({key:"appacitive-environment",value:d.Appacitive.session.environment})}})})(window||process);
(function(d){d.Appacitive.queries={};var e=function(a){a=a||{};this.pageNumber=a.pageNumber||1;this.pageSize=a.pageSize||200};e.prototype.toString=function(){return"psize="+this.pageSize+"&pnum="+this.pageNumber};var b=function(a){a=a||{};this.orderBy=a.orderBy||"__UtcLastUpdatedDate";this.isAscending="undefined"==typeof a.isAscending?!1:a.isAscending};b.prototype.toString=function(){return"orderBy="+this.orderBy+"&isAsc="+this.isAscending};var a=function(a){var f=a||{};this.pageQuery=new e(a);this.sortQuery=
new b(a);this.type=a.type||"article";this.baseType=a.schema||a.relation;this.filter="";this.extendOptions=function(a){for(var c in a)f[c]=a[c];this.pageQuery=new e(f);this.sortQuery=new b(f)};this.setFilter=function(a){this.filter=a};this.toUrl=function(){var a=d.Appacitive.config.apiBaseUrl+this.type+".svc/"+this.baseType+"/find/all?"+this.pageQuery.toString()+"&"+this.sortQuery.toString();0<this.filter.trim().length&&(a+="&query="+this.filter);return a}};d.Appacitive.queries.SearchAllQuery=function(b){b=
b||{};var f=new a(b);this.toRequest=function(){var a=new d.Appacitive.HttpRequest;a.url=f.toUrl();a.method="get";return a};this.extendOptions=function(){f.extendOptions.apply(f,arguments)}};d.Appacitive.queries.BasicFilterQuery=function(b){b=b||{};var f=new a(b);this.toRequest=function(){var a=new d.Appacitive.HttpRequest;a.url=f.toUrl()+"&properties="+b.filter+"&query="+b.filter;a.method="get";return a};this.extendOptions=function(){f.extendOptions.apply(f,arguments)}};d.Appacitive.queries.GraphQuery=
function(b){b=b||{};var f=new a(b);this.toRequest=function(){var a=new d.Appacitive.HttpRequest;a.url=d.Appacitive.config.apiBaseUrl;a.url+=d.Appacitive.storage.urlFactory.article.getProjectionQueryUrl();a.method="post";a.data=b.graphQuery;return a};this.extendOptions=function(){f.extendOptions.apply(f,arguments)}};d.Appacitive.queries.ConnectedArticlesQuery=function(b){b=b||{};var f=new a(b);this.toRequest=function(){var a=new d.Appacitive.HttpRequest;a.url=d.Appacitive.config.apiBaseUrl+"connection/"+
b.relation+"/"+b.articleId+"/find?"+f.pageQuery.toString()+"&"+f.sortQuery.toString();return a};this.extendOptions=function(){f.extendOptions.apply(f,arguments)};this.setFilter=function(){f.setFilter.apply(f,arguments)}}})(window||process);
(function(d){d.Appacitive.BaseObject=function(e){_snapshot=null;var b=e=e||{};this.fetch=function(a,c){a=a||function(){};c=c||function(){};if(b.__id){var e=this,h=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory[this.type].getGetUrl(b.__schematype||b.__relationtype,b.__id),g=new d.Appacitive.HttpRequest;g.url=h;g.method="get";g.onSuccess=function(d){if(d&&d.article){_snapshot=d.article;b.__id=d.article.__id;for(var g in d.article)"undefined"==typeof b[g]&&(b[g]=d.article[g]);e.___collection&&
"article"==e.___collection.collectionType&&e.___collection.addToCollection(e);a()}else c()};d.Appacitive.http.send(g)}else c()};this.del=function(a,c,e){a=a||function(){};c=c||function(){};e=e||{};if(b.__id){var h=this,g=d.Appacitive.config.apiBaseUrl,g=g+d.Appacitive.storage.urlFactory[this.type].getDeleteUrl(b.__schematype||b.__relationtype,b.__id);b&&(b.__schematype&&"user"==b.__schematype.toLowerCase())&&(g=d.Appacitive.config.apiBaseUrl,g+=d.Appacitive.storage.urlFactory.user.getUserDeleteUrl(b.__id));
e.deleteConnections&&!0==e.deleteConnections&&(g=-1==g.indexOf("?")?g+"?deleteconnections=true":g+"&deleteconnections=true");e=new d.Appacitive.HttpRequest;e.url=g;e.method="delete";e.onSuccess=function(d){"200"==d.code?(h.___collection&&h.___collection.removeById(b.__id),a()):c()};e.beforeSend=function(a){console.log("DELETE: "+a.url)};d.Appacitive.http.send(e)}else this.___collection.removeByCId(this.__cid),a()};this.getArticle=function(){return b};this.attributes=function(){if(0==arguments.length)return b.__attributes||
(b.__attributes={}),b.__attributes;if(1==arguments.length)return b.__attributes||(b.__attributes={}),b.__attributes[arguments[0]];if(2==arguments.length)b.__attributes||(b.__attributes={}),b.__attributes[arguments[0]]=arguments[1];else throw Error(".attributes() called with an incorrect number of arguments. 0, 1, 2 are supported.");};this.aggregates=function(){var a={},c;for(c in b){if(!b.hasOwnProperty(c))return;"$"==c[0]&&(a[c]=b[c])}if(0==arguments.length)return a;if(1==arguments.length)return a[arguments[0]];
throw Error(".aggregates() called with an incorrect number of arguments. 0, and 1 are supported.");};this.get=function(a){if(a)return b[a]};this.set=function(a,c){a&&(b[a]=c);return c};this.save=function(d,e){b.__id?a.apply(this,arguments):c.apply(this,arguments)};var a=function(a,c){var e=!1,h=JSON.parse(JSON.stringify(_snapshot)),g;for(g in b)"undefined"==typeof b[g]||null==b[g]?(h[g]=null,e=!0):b[g]!=_snapshot[g]?(h[g]=b[g],e=!0):b[g]==_snapshot[g]&&delete h[g];e&&(e=new d.Appacitive.HttpRequest,
e.url=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory[this.type].getUpdateUrl(b.__schematype,_snapshot.__id),e.method="post",e.data=h,e.onSuccess=function(b){b&&(b.article||b.connection||b.user)?(_snapshot=b.article,"function"==typeof a&&a()):"function"==typeof c&&c()},d.Appacitive.http.send(e))},c=function(a,c){var e=this,h=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory[this.type].getCreateUrl(b.__schematype||b.__relationtype);b.__schematype&&"user"==b.__schematype.toLowerCase()&&
(h=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory.user.getCreateUserUrl());var g=new d.Appacitive.HttpRequest;g.url=h;g.method="put";g.data=b;g.onSuccess=function(d){var g=null;d&&(g=d.article||d.connection||d.user);if(d&&g){_snapshot=g;b.__id=g.__id;for(var h in g)"undefined"==typeof b[h]&&(b[h]=g[h]);e.connectionCollections&&0<e.connectionCollections.length&&e.connectionCollections.forEach(function(a){a.getQuery().extendOptions({articleId:b.__id})});"function"==typeof a&&a()}else"function"==
typeof c&&c()};d.Appacitive.http.send(g)}}})(window||process);
(function(d){var e=function(){return Math.floor(65536*Math.random()).toString(16)};d.Appacitive.GUID=function(){var b=e()+e()+"-"+e()+"-"+e()+"-"+e()+"-"+e()+e()+e(),a="",c,d,j,k,h,g,l=0,b=b.replace(/\r\n/g,"\n");d="";for(j=0;j<b.length;j++)k=b.charCodeAt(j),128>k?d+=String.fromCharCode(k):(127<k&&2048>k?d+=String.fromCharCode(k>>6|192):(d+=String.fromCharCode(k>>12|224),d+=String.fromCharCode(k>>6&63|128)),d+=String.fromCharCode(k&63|128));for(b=d;l<b.length;)c=b.charCodeAt(l++),d=b.charCodeAt(l++),
j=b.charCodeAt(l++),k=c>>2,c=(c&3)<<4|d>>4,h=(d&15)<<2|j>>6,g=j&63,isNaN(d)?h=g=64:isNaN(j)&&(g=64),a=a+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);return a.toString()}})(window||process);
(function(d){d.Appacitive.ArticleCollection=function(e){var b=null,a=null,c=[],f=e;this.collectionType="article";if(!e||!e.schema)throw Error("Must provide schema while initializing ArticleCollection.");var j=this,k=function(c){b=c.schema;c.type="article";a=new d.Appacitive.queries.SearchAllQuery(c);j.extendOptions=a.extendOptions;f=c};this.setFilter=function(c){f.filter=c;f.type="article";f.schema=b;a=new d.Appacitive.queries.BasicFilterQuery(e)};this.reset=function(){b=f=null;c.length=0;a=null};
this.getQuery=function(){return a};this.setOptions=k;k(e);this.get=function(a){if(a!=parseInt(a))return null;a=parseInt(a);return"number"!=typeof a||a>=c.length?null:c.slice(a,a+1)[0]};this.addToCollection=function(a){if(!a||a.get("__schematype")!=b)throw Error("Null article passed or schema type mismatch");var d=null;c.forEach(function(b,c){b.get("__id")==a.get("__id")&&(d=c)});null!=d?c.splice(d,1):c.push(a)};this.getArticle=function(a,b,d){b=b||function(){};d=d||function(){};var e=c.filter(function(b){return b.get("__id")==
a});1==e.length?b(Array.prototype.slice.call(e)[0]):d()};this.getAll=function(){return Array.prototype.slice.call(c)};this.removeById=function(a){if(!a)return!1;var b=null;c.forEach(function(c,d){c.getArticle().__id&&c.getArticle().__id==a&&(b=d)});return null!=b?(c.splice(b,1),!0):!1};this.removeByCId=function(a){if(!a)return!1;var b=null;c.forEach(function(c,d){c.__cid&&c.__cid==a&&(b=d)});return null!=b?(c.splice(b,1),!0):!1};j=this;this.fetch=function(b,e){b=b||function(){};e=e||function(){};
c.length=0;var f=a.toRequest();f.onSuccess=function(a){var f=b;if(a=a.articles){if(!a.length||0==a.length)a=[];a.forEach(function(a){a=new d.Appacitive.Article(a);a.___collection=j;c.push(a)});f()}else e()};d.Appacitive.http.send(f)};this.createNewArticle=function(a){a=a||{};a.__schematype=b;a=new d.Appacitive.Article(a);a.___collection=j;a.__cid=parseInt(1E6*Math.random());c.push(a);return a};this.map=function(){return c.map.apply(this,arguments)};this.forEach=function(){return c.forEach.apply(this,
arguments)};this.filter=function(){return c.filter.apply(this,arguments)}}})(window||process);
(function(d){d.Appacitive.ConnectionCollection=function(e){var b=null,a=null,c=[],f=[],j=e;this.collectionType="connection";if(!e||!e.relation)throw Error("Must provide relation while initializing ConnectionCollection.");var k=function(c){b=c.relation;c.type="connection";a=new d.Appacitive.queries.SearchAllQuery(c);j=c};this.setFilter=function(c){j.filter=c;j.type="connection";j.relation=b;a=new d.Appacitive.queries.BasicFilterQuery(e)};this.setQuery=function(b){if(!b)throw Error("Invalid query passed to connectionCollection");
c.length=0;a=b};this.reset=function(){b=j=null;articles.length=0;c.length=0;a=null};this.getQuery=function(){return a};this.setOptions=k;k(e);this.get=function(a){if(a!=parseInt(a))return null;a=parseInt(a);return"number"!=typeof a||a>=c.length?null:c.slice(a,a+1)[0]};this.addToCollection=function(a){if(!a||a.get("__relationtype")!=b)throw Error("Null connection passed or relation type mismatch");var d=null;c.forEach(function(b,c){b.get("__id")==a.get("__id")&&(d=c)});null!=d?c.splice(d,1):c.push(a)};
this.getConnection=function(a,b,d){b=b||function(){};d=d||function(){};var e=c.filter(function(b){return b.get("__id")==a});1==e.length?b(Array.prototype.slice.call(e)[0]):d()};this.getAll=function(){return Array.prototype.slice.call(c)};this.removeById=function(a){if(!a)return!1;var b=null;c.forEach(function(c,d){c.getConnection().__id&&c.getConnection().__id==a&&(b=d)});return null!=b?(c.splice(b,1),!0):!1};this.removeByCId=function(a){if(!a)return!1;var b=null;c.forEach(function(c,d){c.__cid&&
c.__cid==a&&(b=d)});return null!=b?(c.splice(b,1),!0):!1};var h=this;this.getConnectedArticle=function(a){if(!f||0==f.length)return null;var b=f.filter(function(b){return b.get("__id")==a});return 0<b.length?b[0]:null};this.fetch=function(b,e){b=b||function(){};e=e||function(){};c.length=0;var j=a.toRequest();j.onSuccess=function(a){a:{var j=b;a=a||{};var k=a.connections;if(!k)if(a.status&&a.status.code&&"200"==a.status.code)k=[];else{e();break a}if(!k.length||0==k.length)k=[];k.forEach(function(a){var b=
new d.Appacitive.Connection(a);b.___collection=h;c.push(b);if(a.__endpointa.article||a.__endpointb.article)a=new d.Appacitive.Article(a.__endpointa.article||a.__endpointb.article),a.___collection=h,f.push(a)});j()}};d.Appacitive.http.send(j)};this.createNewConnection=function(a){a=a||{};a.__relationtype=b;a=new d.Appacitive.Connection(a);a.___collection=h;a.__cid=parseInt(1E6*Math.random());c.push(a);return a};this.map=function(){return c.map.apply(this,arguments)};this.forEach=function(a,b){return c.forEach(a,
b||this)};this.filter=function(){return c.filter.apply(this,arguments)}}})(window||process);
(function(d){var e=function(b,a){var c=new d.Appacitive.HttpRequest;c.method="get";c.url=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory.user.getGetAllLinkedAccountsUrl(this.get("__id"));c.onSuccess=function(c){var d=null;c&&(c.identities&&0<c.identities.length)&&(c=c.identities.filter(function(a){return"facebook"==a.authtype.toLowerCase()}),1==c.length&&(d=c[0].username));null!=d?FB.api("/"+d,function(c){c?b(c):a()}):a()};c.onError=function(){a()};d.Appacitive.http.send(c)};d.Appacitive.Article=
function(b){b=new Appacitive.BaseObject(b);b.type="article";b.connectionCollections=[];b.get("__schematype")&&"user"==b.get("__schematype").toLowerCase()&&(b.getFacebookProfile=e);return b};d.Appacitive.BaseObject.prototype.getConnectedArticles=function(b){if("article"!=this.type)return null;b=b||{};b.articleId=this.get("__id");var a=new d.Appacitive.ConnectionCollection({relation:b.relation});a.connectedArticle=this;this.connectionCollections.push(a);b=new d.Appacitive.queries.ConnectedArticlesQuery(b);
a.setQuery(b);return a};d.Appacitive.BaseObject.prototype.getConnected=function(b){if("article"==!this.type)return null;b=b||{};b.onSuccess=b.onSuccess||function(){};b.onError=b.onError||function(){};b.articleId=this.get("__id")}})(window||process);
(function(d){var e=function(b){var a={label:b.label};if(b.articleid)a.articleid=b.articleid;else if(b.article&&"function"==typeof b.article.getArticle)b.article.get("__id")?a.articleid=b.article.get("__id"):a.article=b.article.getArticle();else if("object"==typeof b.article&&b.article.__schematype)b.article.__id?a.articleid=b.article.__id:a.article=b.article;else throw Error("Incorrectly configured endpoints provided to setupConnection");return a};d.Appacitive.Connection=function(b){var a=new Appacitive.BaseObject(b);
a.type="connection";a.getConnection=a.getArticle;a.__defineGetter__("connectedArticle",function(){if(!a.___collection.connectedArticle)throw Error("connectedArticle can be accessed only by using the getConnectedArticles call");var b=a.___collection.connectedArticle.get("__id");if(!b)return null;var d=a.getConnection().__endpointa.articleid;a.getConnection().__endpointa.articleid==b&&(d=a.getConnection().__endpointb.articleid);return a.___collection.getConnectedArticle(d)});a.setupConnection=function(b,
d){if(!b||!b.id||b.label||!d||!d.id||d.label)throw Error("Incorrect endpoints configuration passed.");a.set("__endpointa",e(b));a.set("__endpointb",e(d))};return a}})(window||process);
(function(d){d.Appacitive.Users=new function(){authenticatedUser=null;this.__defineGetter__("currentUser",function(){return authenticatedUser});this.deleteCurrentUser=function(d,b){if(null==authenticatedUser)throw Error("Current user is not set yet");this.deleteUser(authenticatedUser.__id,d||function(){},b||function(){})};this.deleteUser=function(e,b,a){b=b||function(){};a=a||function(){};var c=new d.Appacitive.HttpRequest;c.method="delete";c.url=d.Appacitive.config.apiBaseUrl;c.url+=d.Appacitive.storage.urlFactory.user.getUserDeleteUrl(e);
c.onSuccess=function(c){c&&c.code&&"200"==c.code?b(c):(c=c||{},c.message=c.message||"Server error",a(c))};c.onError=a;d.Appacitive.http.send(c)};this.createUser=function(e,b,a){b=b||function(){};a=a||function(){};e=e||{};e.__schematype="user";if(!e.username||!e.password)throw Error("Username and password are mandatory");var c=new d.Appacitive.HttpRequest;c.method="put";c.url=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory.user.getCreateUserUrl();console.log("SAVE: "+c.url);c.data=e;
c.onSuccess=function(c){c&&c.user?b(c.user):a((c||{}).status||"No response from APIs.")};c.onError=a;d.Appacitive.http.send(c)};this.authenticateUser=function(e,b,a){b=b||function(){};a=a||function(){};var c=new d.Appacitive.HttpRequest;c.method="post";c.url=d.Appacitive.config.apiBaseUrl+d.Appacitive.storage.urlFactory.user.getAuthenticateUserUrl();c.data=e;c.onSuccess=function(c){c&&c.user?(authenticatedUser=c.user,b(c)):(c=c||{},a(c.status))};c.onError=a;d.Appacitive.http.send(c)};this.authenticateWithFacebook=
this.signupWithFacebook=function(d,b){d=d||function(){};b=b||function(){};FB.api("/me",function(){var a={accesstoken:Appacitive.facebook.accessToken,type:"facebook",expiry:3600,attempts:-1,createnew:!0},c=new Appacitive.HttpRequest;c.url=Appacitive.config.apiBaseUrl+Appacitive.storage.urlFactory.user.getAuthenticateUserUrl();c.method="post";c.data=a;c.onSuccess=function(a){a.user?(authenticatedUser=a.user,d(a)):b(a)};c.onError=function(){b()};Appacitive.http.send(c)})}}})(window||process);
(function(d){d.Appacitive.email=new function(){var e={username:null,from:null,frompassword:null,smtphost:"smtp.google.com",smtpport:587,enablessl:!0,replyto:null};this.getConfig=function(){return e};this.sendTemplatedEmail=function(){throw Error("Not implemented yet");};this.setupEmail=function(b){b=b||{};e.username=b.username||e.username;e.from=b.from||e.from;e.frompassword=b.frompassword||e.frompassword;e.smtphost=b.smtphost||e.smtphost;e.smtpport=b.smtpport||e.smtpport;e.enablessl=b.enablessl||
e.enablessl;e.replyto=b.replyto||e.replyto};this.sendRawEmail=function(b,a,c){a=a||function(){};c=c||function(){};if(!b||!b.to||!b.to.length||1==!b.to.length)throw Error("Atleast one receipient is mandatory to send an email");if(!b.subject)throw Error("Subject is mandatory to send an email");b={configuration:e,to:b.to||[],cc:b.cc||[],bcc:b.bcc||[],subject:b.subject||"Appacitive",body:{BodyText:b.body||"",IsBodyHTML:!0,__type:"RawBody"}};var f=new d.Appacitive.HttpRequest;f.url=d.Appacitive.config.apiBaseUrl+
Appacitive.storage.urlFactory.email.getSendEmailUrl();f.method="post";f.data=b;f.onSuccess=function(b){b&&b.status&&"200"==b.status.code?a(b.email):(b=b||{},b.status=b.status||{},c(b.status.message||"Server error"))};d.Appacitive.http.send(f)}}})(window||process);
(function(d){d.Appacitive.facebook=new function(){_accessToken=null;this.requestLogin=function(d,b){d=d||function(){};b=b||function(){};FB?FB.login(function(a){a.authResponse?(_accessToken=a.authResponse.accessToken,d(a.authResponse)):b()},{scope:"email,user_birthday"}):b()};this.getCurrentUserInfo=function(d,b){d=d||function(){};b=b||function(){};FB.api("/me",function(a){a?d(a):b()})};this.__defineGetter__("accessToken",function(){return _accessToken});this.__defineSetter__("accessToken",function(d){_accessToken=
d});this.getProfilePictureUrl=function(d){return"https://graph.facebook.com/"+d+"/picture"};this.logout=function(d,b){d=d||function(){};b=b||function(){};try{FB.logout(function(){d()})}catch(a){b(a.message)}}}})(window||process);